#!/bash/sh

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_and_run() {
       echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

check_and_run requirements.txt  "pip install --upgrade pip &&" \
"( pip install --no-cache-dir -r requirements.txt  ||" \
  "pip3 install --no-cache-dir -r requirements.txt ||" \
  "python -m pip install --no-cache-dir -r requirements.txt  ||" \
  "python3 -m pip install --no-cache-dir -r requirements.txt )"
