#!/bash/sh

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_and_run() {
       echo "$changed_files" | grep --quiet "$1" && eval "$2"
}

pip install --upgrade pip  || \
pip3 install --upgrade pip || \
python -m pip --upgrade pip  || \
python3 -m pip --upgrade pip

check_and_run requirements.txt  "pip install --upgrade pip &&" \
"( pip install --no-cache-dir -r requirements.txt  ||" \
  "pip3 install --no-cache-dir -r requirements.txt ||" \
  "python -m pip install --no-cache-dir -r requirements.txt  ||" \
  "python3 -m pip install --no-cache-dir -r requirements.txt )"

check_and_run HTML  "pip install --upgrade pip &&" \
"( pip install --no-cache-dir -e HTML  ||" \
  "pip3 install --no-cache-dir -e HTML ||" \
  "python -m pip install --no-cache-dir -e HTML  ||" \
  "python3 -m pip install --no-cache-dir -e HTML )"
